let player;
let background;
let myScore;
let highestSocre;
let key = false;
let obstacles = [];
let obstaclesInvisible = [];
let timeUpdate;
let bullet = [];
let flappy_Bird = [];
const PLAYER_WIDTH = 60;
const PLAYER_HEIGHT = 60;
const GAME_AREA_WIDTH = 780;
const GAME_AREA_HEIGHT = 420;
const BACKGROUND_WIDTH = 720;
const BACKGROUND_HEIGHT = 420;
const POSITION_X = 0;
const POSITION_Y = GAME_AREA_HEIGHT/2 - PLAYER_HEIGHT/2;
